eureka:
  instance:
    hostname: localhost
    secure-port-enabled: true
    secure-port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
  username: eureka
  password: password

server:
  port: 8761
  ssl:
    key-store: store/keystore.jks
    key-store-password: winted
    key-alias: localhost
    key-password: winted
    enabled: true
