spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: winted-profile-service
      username: winted-profile-service
      password: winted-profile-service
  application:
    name: profile-service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: notificationTopic
    bootstrap-servers:
      - http://kafka:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8000/realms/winted # questo deve coincidere con l'url che usano i client
          jwk-set-uri: http://keycloak:8080/realms/winted/protocol/openid-connect/certs # solo questo deve essere raggiungibile da spring
          introspection-uri: http://keycloak:8080/realms/winted/protocol/openid-connect/token/introspect
          client-id: winted-web
          client-secret: 0tWCKy4mShRYeQjw8TMMISsGQDEQJmYB

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka:password@eureka:8761/eureka

server:
  port: 0

logging:
  level:
    it.pingflood.winted: "debug"

springdoc:
  packagesToScan: it.pingflood.winted.profileservice
  api-docs:
    path: /api/v1/profile/v3/api-docs
  swagger-ui:
    path: /api/v1/profile/swagger-ui.html
