spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    mongodb:
    uri: mongodb://localhost:27017/winted-profile-service
  application:
    name: profile-service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: notificationTopic
    bootstrap-servers:
      - localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8000/realms/winted
        opaquetoken:
          introspection-uri: https://localhost:8000/realms/winted/protocol/openid-connect/token/introspect
          client-id: winted-web
          client-secret: 0tWCKy4mShRYeQjw8TMMISsGQDEQJmYB

eureka:
  instance:
    hostname: localhost
    securePortEnabled: true
  client:
    serviceUrl:
      defaultZone: https://eureka:password@localhost:8761/eureka

server:
  port: 0
  ssl:
    key-store: store/keystore.jks
    key-store-password: winted
    key-alias: localhost
    key-password: winted
    enabled: true

logging:
  level:
    #    root: "warn"
    #    org.springframework.web: "warn"
    #    org.hibernate: "debug"
    it.pingflood.winted: "debug"

springdoc:
  packagesToScan: it.pingflood.winted.profileservice
  api-docs:
    path: /api/v1/profile/v3/api-docs
  swagger-ui:
    path: /api/v1/profile/swagger-ui.html
