spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    mongodb:
    uri: mongodb://localhost:27017/winted-product-service
  application:
    name: product-service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: notificationTopic
    bootstrap-servers:
      - localhost:9092


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 0


logging:
  level:
    #    root: "warn"
    #    org.springframework.web: "warn"
    #    org.hibernate: "debug"
    it.pingflood.winted: "debug"
