spring:
  data:
    mongodb:
    uri: mongodb://localhost:27017/winted-product-service
  application:
    name: product-service

eureka:
  client:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka

server:
  port: 0
