eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka:8761/eureka

server:
  port: 0
spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  application:
    name: resource-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/winted-resource-service?allowMultiQueries=true
    username: winted-resource-service
    password: winted-resource-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "warn"
    it.pingflood.winted: "debug"

app:
  aws:
    s3:
      bouquetName: "winted-resource"
    credential:
      accessKey: 'AKIAVFWIQUJXGMLH5U5F'
      secretKey: "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"

springdoc:
  packagesToScan: it.pingflood.winted.resourceservice
  api-docs:
    path: /api/v1/resource/v3/api-docs
  swagger-ui:
    path: /api/v1/resource/swagger-ui.html

management:
  health:
    redis:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - httptrace
          - logfile
      base-path: /api/v1/resource/actuator
