spring:
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8000/realms/winted
          jwk-set-uri: https://localhost:8000/realms/winted/protocol/openid-connect/certs
          introspection-uri: https://localhost:8000/realms/winted/protocol/openid-connect/token/introspect
          client-id: winted-web
          client-secret: 0tWCKy4mShRYeQjw8TMMISsGQDEQJmYB
  data:
    mongodb:
      uri: "mongodb://localhost:27017/winted-message-service"
  application:
    name: message-service
  kafka:
    consumer:
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers:
      - localhost:9092
  jackson:
    deserialization:
      read-unknown-enum-values-as-null: false
eureka:
  instance:
    hostname: localhost
    securePortEnabled: true
  client:
    serviceUrl:
      defaultZone: https://eureka:password@localhost:8761/eureka

server:
  port: 0
  ssl:
    key-store: store/keystore.jks
    key-store-password: winted
    key-alias: localhost
    key-password: winted
    enabled: true
logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "warn"
    it.pingflood.winted: "debug"


springdoc:
  packagesToScan: it.pingflood.winted.messageservice
  api-docs:
    path: /api/v1/message/v3/api-docs
  swagger-ui:
    path: /api/v1/message/swagger-ui.html
