spring:
  data:
  mongodb:
    host: localhost
    port: 27017
    database: winted-message-service
  application:
    name: message-service

eureka:
    client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0
