spring:
  data:
  mongodb:
    uri: "mongodb://localhost:27017/ciao"
  application:
    name: message-service

eureka:
  client:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka

server:
  port: 8001

logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "warn"
    it.pingflood.winted: "debug"
