spring:
  data:
  mongodb:
    uri: "mongodb://localhost:27017/ciao"
  application:
    name: message-service
  kafka:
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
    template:
      default-topic: notificationTopic
    bootstrap-servers:
      - localhost:9092


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 0

logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "warn"
    it.pingflood.winted: "debug"
