eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 0

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/winted-order-service
    username: winted-order-service
    password: winted-order-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: notificationTopic
    bootstrap-servers:
      - localhost:9092

logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "warn"
    it.pingflood.winted: "debug"
